import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Note } from './types';
import { format } from 'date-fns';

interface NoteForPdf extends Note {
  topicName: string;
}

// Function to add a header to each page
const addHeader = (doc: jsPDF, pageNum: number, totalPages: number, topicName: string) => {
  doc.setFontSize(9);
  doc.setTextColor('#666666');
  doc.text(topicName, 25, 20);
  doc.text(`Page ${pageNum} of ${totalPages}`, doc.internal.pageSize.getWidth() - 25, 20, { align: 'right' });
  
  if (pageNum === 1) {
    doc.setDrawColor('#dddddd');
    doc.line(25, 25, doc.internal.pageSize.getWidth() - 25, 25);
  }
};

// Function to add a footer
const addFooter = (doc: jsPDF) => {
  doc.setFontSize(8);
  doc.setTextColor('#aaaaaa');
  doc.text('Generated by CodeNote', doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 15, { align: 'center' });
};

const createStyledContainer = () => {
    const container = document.createElement('div');
    document.body.appendChild(container);

    Object.assign(container.style, {
        position: 'absolute',
        left: '-9999px',
        top: '0px',
        width: '780px', // A4-like width for rendering
        padding: '0',
        margin: '0',
        backgroundColor: '#ffffff',
        color: '#000000',
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    });
    return container;
}


const renderNoteContent = (note: NoteForPdf, isMultiNoteExport: boolean): string => {
    const createdAt = note.createdAt?.toDate ? format(note.createdAt.toDate(), 'PPP') : 'N/A';
    const updatedAt = note.updatedAt?.toDate ? format(note.updatedAt.toDate(), 'PPP') : 'N/A';

    let contentHtml = note.highlightedContent || note.content;

    // For code notes, ensure highlighted content is wrapped correctly for styling
    if (note.type === 'code' && !contentHtml.startsWith('<pre')) {
       contentHtml = `<pre><code>${contentHtml}</code></pre>`;
    }

    return `
        <div class="pdf-note-container" style="${isMultiNoteExport ? 'page-break-before: always;' : ''}">
            <h1 class="note-title">${note.title}</h1>
            <div class="metadata">
                <span>Created: ${createdAt}</span>
                <span>Last Updated: ${updatedAt}</span>
            </div>
            <div class="content-body">${contentHtml}</div>
        </div>
    `;
};


export const generatePdf = async (notes: NoteForPdf[]) => {
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'px',
    format: 'a4',
  });

  const container = createStyledContainer();
  
  const style = document.createElement('style');
  style.innerHTML = `
    body { margin: 0; padding: 0; }
    .pdf-note-container {
        box-sizing: border-box;
        width: 100%;
        padding: 20px 30px;
        page-break-inside: avoid;
    }
    .note-title { 
        font-size: 28px; 
        margin-top: 20px;
        margin-bottom: 8px; 
        font-weight: 700;
        font-family: "Space Grotesk", sans-serif;
        color: #111827;
    }
    .metadata { 
        font-size: 11px; 
        color: #4b5563; 
        margin-bottom: 20px; 
    }
    .metadata span {
        margin-right: 15px;
    }
    .content-body { 
        font-size: 12px; 
        line-height: 1.6;
        color: #374151;
    }
    /* General content styling from tiptap */
    .content-body > * + * { margin-top: 0.75em; }
    .content-body ul, .content-body ol { padding-left: 1.5rem; }
    .content-body hr { margin: 1rem 0; border-color: #e5e7eb; }
    .content-body blockquote { padding-left: 1rem; border-left: 3px solid #d1d5db; font-style: italic; }
    .content-body a { color: #2563eb; text-decoration: underline; }
    .content-body h1, .content-body h2, .content-body h3 { font-family: "Space Grotesk", sans-serif; margin-bottom: 0.5em; font-weight: 600; }
    .content-body h1 { font-size: 1.5em; }
    .content-body h2 { font-size: 1.25em; }
    .content-body h3 { font-size: 1.1em; }

    /* Code block specific styling for syntax highlighting */
    .content-body pre {
        background-color: #f3f4f6;
        color: #111827;
        font-family: "Source Code Pro", "Courier New", Courier, monospace;
        font-size: 11px;
        border: 1px solid #e5e7eb;
        border-radius: 6px;
        padding: 12px;
        white-space: pre-wrap;
        word-break: break-all;
        overflow-x: auto;
        margin: 16px 0;
    }
    .content-body pre code {
        white-space: pre-wrap !important;
        background: transparent !important;
        padding: 0 !important;
        font-size: inherit !important;
    }
    /* Syntax highlighting colors (basic example) */
    .token.comment, .token.prolog, .token.doctype, .token.cdata { color: #6a737d; }
    .token.punctuation { color: #6a737d; }
    .token.property, .token.tag, .token.boolean, .token.number, .token.constant, .token.symbol, .token.deleted { color: #d73a49; }
    .token.selector, .token.attr-name, .token.string, .token.char, .token-inserted { color: #032f62; }
    .token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string { color: #d73a49; }
    .token.atrule, .token.attr-value, .token.keyword { color: #d73a49; }
    .token.function, .token.class-name { color: #6f42c1; }
    .token.regex, .token.important, .token.variable { color: #e36209; }
  `;
  container.appendChild(style);

  let fullHtml = style.outerHTML;
  notes.forEach((note, index) => {
      fullHtml += renderNoteContent(note, index > 0);
  });
  container.innerHTML = fullHtml;

  const pdfWidth = doc.internal.pageSize.getWidth();
  const pdfHeight = doc.internal.pageSize.getHeight();
  const canvas = await html2canvas(container, {
      scale: 2, // Higher scale for better quality
      useCORS: true,
      logging: false,
      width: container.scrollWidth,
      height: container.scrollHeight,
      windowWidth: container.scrollWidth,
      windowHeight: container.scrollHeight,
  });

  document.body.removeChild(container);

  const imgData = canvas.toDataURL('image/png');
  const imgProps = doc.getImageProperties(imgData);
  const imgWidth = pdfWidth;
  const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
  let heightLeft = imgHeight;
  let position = 0;
  let pageNum = 1;
  const topicName = notes.length > 0 ? notes[0].topicName : "CodeNote Export";

  doc.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
  heightLeft -= pdfHeight;

  while (heightLeft > 0) {
    position -= pdfHeight;
    doc.addPage();
    doc.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;
  }
  
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addHeader(doc, i, totalPages, topicName);
    addFooter(doc);
  }
  
  const safeFilename = notes.length === 1 
    ? notes[0].title.replace(/[^a-z0-9]/gi, '_').toLowerCase() 
    : 'codenote-export';
  doc.save(`${safeFilename}.pdf`);
};
